from coredatastruct.datastruct import SinglyLinkedList
list1 = SinglyLinkedList()
list1.create_newnode(10)
list1.display()
list1.add_node_rear(20)
list1.display()
list1.remove_rear()
list1.display()
list1.add_node_rear(30)
list1.display()
#list1.remove_front()
list1.display()
list1.append_front(0)
list1.display()
print(list1.len())
#list1.append_front(40)
#print(list1.len())
list1.insert(2,20)
list1.display()
list1.insert(0,110)
list1.display()